### PR TITLE
Cluster credentials

### PR DESCRIPTION
**Pull request by carolynvs**
I'm still working on the code (i.e. it doesn't do what I say below yet), but wanted to share the direction I'm looking in to address https://github.com/getcarina/feedback/issues/39. 

* Keep existing oauth dance flow the same.
* When authenticating to identity, keep the temporary auth token in the user model, but do not expose it via `/me`.
* Add scopes: identity (default), get cluster credentials, and create cluster.
* Add endpoint `/clusters` which is protected by doorkeeper.
  * GET `/clusters/:cluster_name` returns the cluster zip file
  * PUT `/clusters/:cluster_name` creates a cluster with the specified name.
      * Poll with GET until the cluster is active to get the credentials.
* `/clusters` uses the identity auth token to interact with Carina.

Example flows:

**Discourse**
Existing oauth dance, implicitly requesting the default scope, identity.

**WordPress Tutorial Site**
1. OAuth dance, requesting the credentials scope.
2. GET `/clusters/tutorials` and receive the credentials for an existing cluster, `tutorials`.
3. Uses the cluster credentials to setup a demo WordPress site on the user's cluster.

**howtowhale.com**
1. OAuth dance, requesting the credentials scope.
2. PUT to `/clusters/howtowhale`. A new cluster named `howtowhale` is created on the user's Carina account.
3. Polls GET `/clusters/howtowhale` until 200 is returned with the credentials zip. Credentials can't be returned until the cluster is active, so this may take a while. Return 404 not found until credentials are ready.
4. Uses the cluster credentials to setup Jupyter on the new cluster.

### CODE REVIEW

**Comment by carolynvs** [comment]
@mdarby How do you want to handle registering oauth applications? A couple options come to mind:

1. Applications are added to the db manually using rake. Doesn't make it easy for new apps to join the oauth party, but is the least effort on our part.

      **db/seeds.rb**
      ```
      app = Doorkeeper::Application.create! :name => "howtowhale.com", :redirect_uri => "https://howtowhale.com/hub/oauth_callback"

      puts "Application: "
      puts "name: #{app.name}"
      puts "redirect_uri: #{app.redirect_uri}"
      puts "uid: #{app.uid}"
      puts "secret: #{app.secret}"
      ```

2. We add the concept of administrators to our user model, hide `/applications` behind an admin check and update `doorkeeper.rb`. Same as the first option, but gives us a UI instead of remembering the magic rake commands.

      **config/doorkeeper.rb**
      ```
      admin_authenticator do
          Admin.find_by_id(session[:admin_id]) || redirect_to(new_admin_session_url)
      end
      ```

3. We customize the controller for `/applications` so that users can't see/edit all applications, only ones that they created. This would be nice long term, as we aren't involved.

**Comment by mdarby** [comment]
I finally fixed :master yesterday -- could you rebase while I grok your comment? :)

**Comment by carolynvs** [comment]
Will do!

**Comment by mdarby** [comment]
I definitely dig the idea of having admin users that can create an OAuth application. Seems we could expose those routes to CRUD the application scoped to the user. IIRC Doorkeeper has an association between User/Application already. I'm not sure we'd need an "admin" flag as any user can have an application and so long as we scope it to their ownership I think we'd be good. Thoughts?

**Comment by carolynvs** [comment]
I would really like to enable all users to make/manage their own apps, like GitHub. If we have that, do we even need the concept of an admin?

**Comment by mdarby** [comment]
Nope! That's the beauty :)

**Comment by carolynvs** [comment]
Cool! I've turned that into a separate issue.

**Comment by carolynvs** [comment]
@mdarby rebased! Here's my todo list for this PR before it is merged:

- [ ] Finish converting my test oauth app to use `/clusters` to make sure there aren't any gaps
- [ ] Refresh the api token if it comes back as expired when we hit the Carina API

I've made separate issues for other stuff:

* #4 - Convert deploy.sh to a Makefile
* #3 - Enable uses to manage their oauth apps

Do you see anything else that must be addressed in this before merging?

**Comment by carolynvs** [comment]
@mdarby I've included api token refreshing and also some tests for the /clusters endpoint. I'll leave you to chew on it and merge if it passes the bar.

**Comment by carolynvs** [comment]
At 2am I woke up and realized that I need a bit more logic for existing users, as they won't be going through the same flow and will be missing the api key. I'll get that in today.

**Comment by carolynvs** [comment]
I've updated the PR so that we can better handle the migration for existing users:

1. When we deploy, change the secret_key_base.

    This will force existing sessions to expire. This is necessary because we use cookie based sessions,
    and they are good forever. I need to force the cookie to be rejected so that they have to log in again.
2. The next time a user logs in, the session controller checks if the user should reauthenticate against the identity provider.

    Reauthentication is triggered only if the user is missing important data (in this case, the api_key). After reauth, the user model is updated with the latest data from the identity provider.

**Comment by mdarby** [comment]
Looks awesome. :)

**Pull request merged**
