### PR TITLE
Fix current_resource_owner

### PR DESCRIPTION
**Pull request by carolynvs**
Enable calling current_resource_owner from page _and_ api controllers, by including both doorkeeper and devise logic for finding the current user.

### CODE REVIEW

**Comment by mdarby** [comment]
Can you rebase this? Seems to have conflicted with your earlier PR :)

**Comment by carolynvs** [comment]
Oops, rebase gone awry, please don't merge. Give me a minute to fix.

**Comment by carolynvs** [comment]
Okay all fixed! I didn't intend for that second commit to be in this PR. :blush:

**Comment by mdarby** [comment]
:metal:

**Pull request merged**
